version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    # Volúmenes para que el código se recargue (Hot-Reload) en local
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    # Volúmenes para que Vite detecte los cambios de React automáticamente
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
