version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quizztrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://admin:password123@db:5432/quizztrack?schema=public
      - JWT_SECRET=quizztrack_mvp_super_secret_key
      - PORT=4000
    depends_on:
      - db
    # Volúmenes para que el código se recargue (Hot-Reload) en local
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # Volúmenes para que Vite detecte los cambios de React automáticamente
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
